Add CI step to create a issue from a PR
k3s-io/k3s pull request #10277
Opened 2024-06-03 18:49 UTC by vitorsavian

#### Proposed Changes ####

- New CI step for new PRs

#### Types of Changes ####

- Feature

#### Verification ####

#### Testing ####

#### Linked Issues ####

- https://github.com/k3s-io/k3s/issues/9272

#### User-Facing Change ####

```release-note

```

#### Further Comments ####

2024-10-18 15:47 UTC, dereknola commented
Does this handle the existence of existing linked issues (i.e. I already have a linked issue in the PR body when i open the PR)?

2024-10-18 15:52 UTC, dereknola requested changes
Hiding the logic inside a external action is not super helpful, we should move this within the k3s-org.

2024-10-18 15:52 UTC, dereknola commented on .github/workflows/create-issue-from-pr.yaml
> +name: Create issue from PR
```suggestion
name: Create linked issues for PRs without one
```

2024-10-18 15:52 UTC, dereknola commented on .github/workflows/create-issue-from-pr.yaml
> +      - name: Create issue from PR and verify membership
```suggestion
      - name: Create issue from PR for community members
```

2024-10-18 15:52 UTC, vitorsavian commented
> Does this handle the existence of existing linked issues (i.e. I already have a linked issue in the PR body when i open the PR)?

It does not, I remember Caroline saying something about using this to make we track the PRs using the issues

but I believe it can be done, the steps takes then entire body of the PR

2024-10-22 17:44 UTC, vitorsavian commented
@dereknola I changed the action to entire shell script within the actions, I think it is better instead of having to build Js inside the `.github/actions`

2025-06-10 16:19 UTC, closed without merging