Update flannel to v0.25.4 and fixed issue with IPv6 mask
k3s-io/k3s pull request #10422
Opened 2024-06-28 17:02 UTC by rbrtbnfgl

#### Proposed Changes ####

Bump Flannel version to v0.24.4 and fixes an issue when IPv6masq flag is configuered
#### Types of Changes ####

#### Verification ####

#### Testing ####

#### Linked Issues ####

#10419

#### User-Facing Change ####

```release-note

```

#### Further Comments ####

2024-06-28 17:04 UTC, brandond approved these changes

2024-07-01 06:54 UTC, manuelbuil requested changes

2024-07-01 06:54 UTC, manuelbuil commented on pkg/agent/flannel/flannel.go
> +					logrus.Errorf("Couldn't parse previous %s from subnet file at %s: %s", CIDRKey, path, err)
same

2024-07-01 06:54 UTC, manuelbuil commented on pkg/agent/flannel/flannel.go
> +			logrus.Errorf("Couldn't fetch previous %s from subnet file at %s: %s", CIDRKey, path, err)
same

2024-07-01 07:09 UTC, manuelbuil requested changes
The problem is that it reads the subnet file, e.g.
```
FLANNEL_NETWORK=10.42.0.0/16
FLANNEL_SUBNET=10.42.0.1/24
FLANNEL_IPV6_NETWORK=2001:cafe:42::/56
FLANNEL_IPV6_SUBNET=2001:cafe:42::1/64
FLANNEL_MTU=1450
FLANNEL_IPMASQ=true
```
But there are two IPv6 networks?

2024-07-01 07:09 UTC, manuelbuil commented on pkg/agent/flannel/flannel.go
> +					logrus.Errorf("Couldn't parse previous %s from subnet file at %s: %s", CIDRKey, path, err)
same here, sorry I missed it

2024-07-01 16:45 UTC, dereknola approved these changes

2024-07-01 16:57 UTC, merged