Add data-dir to uninstall and killall scripts
k3s-io/k3s pull request #10473
Opened 2024-07-09 20:59 UTC by jakefhyde

#### Proposed Changes ####

Add `K3S_DATA_DIR` as an optional environment variable to the `k3s-killall` and `k3s-uninstall` script generation within `install.sh`.

#### Types of Changes ####

Bugfix

#### Verification ####

Installing K3s with a custom `data-dir` (not `/var/lib/rancher/k3s`), and running the killall and uninstall scripts, verifying assets in `/var/lib/rancher/k3s` are properly removed.

#### Testing ####

This is not currently covered by testing, though I would be happy to write an integration test if need be.

#### Linked Issues ####

https://github.com/k3s-io/k3s/issues/10471

#### User-Facing Change ####

```release-note
NONE
```

#### Further Comments ####

2024-07-09 21:24 UTC, brandond requested changes
don't forget to update the install script sha256sum file

2024-07-10 07:26 UTC, brandond approved these changes

2024-07-10 13:45 UTC, vitorsavian submitted a review, later dismissed

2024-07-10 16:25 UTC, brandond commented
I think we're good to go, unfortunately I just merged another change to the install script so you'll need to rebase to fix the checksum conflict :(

2024-07-10 17:14 UTC, brandond approved these changes

2024-07-10 17:30 UTC, brandond commented
No backports necessary, as install script is served off master

2024-07-10 17:34 UTC, vitorsavian approved these changes

2024-07-10 19:14 UTC, dereknola approved these changes

2024-07-10 19:46 UTC, brandond commented
centos7 is dead; merging

2024-07-10 19:46 UTC, merged