Use higher QPS for secrets reencryption
k3s-io/k3s pull request #10571
Opened 2024-07-24 23:02 UTC by dereknola

#### Proposed Changes ####
- Use a separate client go for updating secrets, the default wrangler values strangle the throughput of the secrets encryption controller.

#### Types of Changes ####
Feature Enhancement

#### Verification ####
Time to reencrypt 1000 secrets 
| Master | PR | 
| - | - | 
| 207s | 4s |

#### Testing ####
Already Covered

#### Linked Issues ####
TBD

#### User-Facing Change ####

```release-note

```

#### Further Comments ####
This dramatically cuts the time for secrets encryption. It is possible we no longer even need a controller for this task, as even with 10K+ secrets, the timeline is now seconds not tens of minutes.

2024-07-25 01:05 UTC, brandond requested changes

2024-07-25 01:05 UTC, brandond commented on pkg/secretsencrypt/controller.go
> +	cclient       typev1.CoreV1Interface
Other places in the code we just call this `core`, I think.

2024-07-25 01:05 UTC, brandond commented on pkg/secretsencrypt/controller.go
> +		return h.cclient.Secrets(metav1.NamespaceAll).List(h.ctx, metav1.ListOptions{})
I think you need to leave this passing in `opts`. If you pass in a new listoptions then the pagination stuff from the helper is dropped.

2024-07-25 03:15 UTC, brandond commented on pkg/secretsencrypt/controller.go
> +	cclient       typev1.CoreV1Interface
You could probably just make this a `kubernetes.Interface` and keep a reference to `k8s` that is passed in to Register, and call `h.k8s.CoreV1().Secrets()`

2024-07-25 16:35 UTC, brandond approved these changes

2024-07-26 04:31 UTC, vitorsavian approved these changes

2024-07-26 19:07 UTC, merged