Fix etcd backup/restore test and add guardrail for etcd-snapshot
k3s-io/k3s pull request #11314
Opened 2024-11-13 15:58 UTC by manuelbuil

#### Proposed Changes ####

This PR does two things:
1 - Fixes the e2e test doing backup/restore from a snapshot. It was failing with:
```
FATA[0000] cannot perform cluster-reset while server URL is set - remove server from configuration before resetting
```
When comparing the steps it was following and the documentation, it was indeed wrong. The rest of the servers don't have to run `--cluster-reset`. When removing the step `Resets non bootstrap nodes`, the e2e test works again

2 - I must confess that I wasted an hour trying to use `k3s etcd-snapshot` in a k3s cluster that was not using etcd. When doing that, the error we get is super confusing:
```
FATA[0000] see server log for details: Unauthorized
```
However, there is nothing in the logs. The problem is that we are treating a 404 (url does not exist) as Unauthorized https://github.com/k3s-io/k3s/blob/master/pkg/server/router.go#L87. We have been doing that for a long time, so it is probably risky to change that. Therefore, I decided to check if `kine.sock` exists and `db/etcd/config` not in the dataDir. If that's the case, we print `K3s is not deployed with an etcd datastore`

#### Types of Changes ####

Test fix + guardrail

#### Verification ####

1 - Run the e2e test
2 - Run any `k3s etcd-snapshot` command without etcd as datastore

#### Testing ####

#### Linked Issues ####

#### User-Facing Change ####

```release-note

```

#### Further Comments ####

2024-11-13 16:12 UTC, VestigeJ submitted a review, later dismissed

2024-11-13 16:37 UTC, dereknola submitted a review, later dismissed

2024-11-13 16:52 UTC, brandond requested changes
> The problem is that we are treating a 404 (url does not exist) as Unauthorized https://github.com/k3s-io/k3s/blob/master/pkg/server/router.go#L87. 

That's not what's happening here. The NotFoundHandler field is perhaps poorly named, but it is just how mux handles chaining request handlers. If a router handler does not find a matching route, it hands it off to the next handler. In this case you'll notice that section of code setting up a long chain of routers where each router in the chain sets the previous one as its NotFound handler, and the final router is whats returned. Because etcd isn't present to install any routes that match the snapshot path, you end up getting passed all the way through to the apiserver, which is what generates the Unauthorized response.

We do have other handlers that return proper errors if etcd isn't enabled, for example:
https://github.com/k3s-io/k3s/blob/b93fd98a1c733b61ac515e07f4abcaf27d2f6b7f/pkg/server/router.go#L118-L126

Here's where the snapshot handlers are registered:
* https://github.com/k3s-io/k3s/blob/b93fd98a1c733b61ac515e07f4abcaf27d2f6b7f/pkg/cluster/managed.go#L94-L103
* https://github.com/k3s-io/k3s/blob/b93fd98a1c733b61ac515e07f4abcaf27d2f6b7f/pkg/etcd/etcd.go#L632-L633
* https://github.com/k3s-io/k3s/blob/b93fd98a1c733b61ac515e07f4abcaf27d2f6b7f/pkg/etcd/etcd.go#L696-L697

We do not need to worry about returning 404s for the snapshot handlers if etcd isn't enabled, since that's not what's currently happening. Nor should the CLI be checking for etcd datastore files - request validation should happen on the server side.

You could probably do a couple different things:
* Add a default handler in `router.go` that matches /db/ and sends an appropriate error - counting on the fact that the etcd router is later in the chain and the requests won't ever make it to this handler if etcd is running.
* Add a default handler in `managed.go` that is only added if etcd isn't enabled. This is probably technically safer, since it would avoid installing the error handler if etcd is running.

2024-11-14 11:34 UTC, manuelbuil commented
> * Add a default handler in `managed.go` that is only added if etcd isn't enabled. This is probably technically safer, since it would avoid installing the error handler if etcd is running.

Thanks for the explanation and the suggestion. I took this path, I also agree it is safer

2024-11-14 17:07 UTC, brandond requested changes

2024-11-20 09:17 UTC, manuelbuil commented on pkg/cluster/managed.go
> +	})
done! And learnt a lot of things around mux and how to create wildcard routes

2024-11-20 17:54 UTC, brandond requested changes
whitespace nit

2024-11-20 17:54 UTC, brandond commented on pkg/cluster/managed.go
> +    })
inconsistent indentation
```suggestion
	// Wildcard route for anything after /db/
	r.HandleFunc("/db/{_:.*}", func(resp http.ResponseWriter, r *http.Request) { 
		util.SendError(errors.New("etcd datastore disabled"), resp, r, http.StatusBadRequest)
	})
```

2024-11-21 17:29 UTC, cwayne18 commented
/trivy

2024-11-27 22:42 UTC, dereknola approved these changes

2024-11-28 08:40 UTC, merged