Fix K3S_DATA_DIR when running as non-root user
k3s-io/k3s pull request #11378
Opened 2024-11-27 16:35 UTC by unguiculus

#### Proposed Changes ####

When running the generated kill and uninstall scripts, the environment variable `K3S_DATA_DIR` got lost, because `sudo` by default doesn't preserve the environment. This is fixed by adding the `--preserve-env` flag.

#### Types of Changes ####

Bugfix

#### Verification ####

* Set environment variable `K3S_DATA_DIR`. 
* Run the generated `k3s-killall.sh` script as non-root user and check the log output.
* Verify that the `$K3S_DATA_DIR` directory got cleaned.

2024-11-27 19:03 UTC, brandond commented
Thanks for the fix! Can you open an issue describing the problem this fixes, so our QA team can validate that the issue is resolved by this change?

2024-11-28 06:07 UTC, brandond requested changes
I'd prefer to pass through only this one necessary env var, instead of passing through ALL of them.

2024-11-28 06:07 UTC, brandond commented on install.sh
> +[ $(id -u) -eq 0 ] || exec sudo --preserve-env $0 $@
```suggestion
[ $(id -u) -eq 0 ] || exec sudo -E K3S_DATA_DIR $0 $@
```

2024-11-28 06:07 UTC, brandond commented on install.sh
> +[ \$(id -u) -eq 0 ] || exec sudo --preserve-env \$0 \$@
```suggestion
[ \$(id -u) -eq 0 ] || exec sudo -E K3S_DATA_DIR \$0 \$@
```

2024-12-03 04:17 UTC, brandond submitted a review, later dismissed

2024-12-03 08:57 UTC, thomasferrandiz submitted a review, later dismissed

2024-12-19 14:12 UTC, unguiculus commented
Any chance this get's merged soonish? Thanks.

2024-12-19 17:30 UTC, dereknola commented
We are in code freeze for December releases. This will get in for January.

2025-01-09 19:48 UTC, brandond commented
Would you mind rebasing this? Thanks!

2025-01-09 20:37 UTC, unguiculus commented
@brandond Done.

2025-01-09 21:29 UTC, dereknola approved these changes

2025-01-09 21:58 UTC, brandond approved these changes

2025-01-10 18:07 UTC, merged