Automate coredns version bumps with updatecli
k3s-io/k3s pull request #11482
Opened 2024-12-19 14:17 UTC by RokibulHasan7

#### Proposed Changes ####

#### Types of Changes ####

#### Verification ####

#### Testing ####

#### Linked Issues ####
https://github.com/k3s-io/k3s/issues/11392

#### User-Facing Change ####

```release-note

```

#### Further Comments ####

2024-12-19 19:12 UTC, brandond requested changes
Thanks for the contribution! I have a question about the new script though.

2024-12-19 19:12 UTC, brandond commented on updatecli/scripts/run-make-generate.sh
> +git diff
This seems to be essentially the same thing as run-go-generate: 
https://github.com/k3s-io/k3s/blob/83a3e851d3d809c12b24789e28746c0ce4620359/updatecli/scripts/run-go-generate.sh#L5-L7

Is there any particular reason to create a new different version of those same steps?

2024-12-20 17:57 UTC, dereknola approved these changes

2024-12-21 00:03 UTC, brandond commented
We're still in code freeze for the 1.32 release, we will resume merging things soon.

2024-12-23 17:49 UTC, cwayne18 commented
Thank you very much for this!  We'll get it merged as soon as we're out of code freeze, happy holidays!

2025-01-07 22:58 UTC, brandond approved these changes

2025-01-08 18:03 UTC, merged