Update Traefik to v2.11.16
k3s-io/k3s pull request #11502
Opened 2024-12-26 03:23 UTC by muicoder

#11501
Signed-off-by: muicoder <muicoder@gmail.com>

#### Proposed Changes ####

#### Types of Changes ####

#### Verification ####

#### Testing ####

#### Linked Issues ####

#### User-Facing Change ####

```release-note

```

#### Further Comments ####

2024-12-26 17:53 UTC, cwayne18 requested changes
Wish it were this easy :) 

1) That tag does not exist in the rancher namespace in dockerhub at this time
2) You'd need to update the chart in `k3s-io/k3s-charts` as well IIRC

2024-12-26 20:09 UTC, brandond commented
It's OK to update the tag here, but it does need to be mirrored first, and you need to `make download generate` and check in the resulting changes.

2024-12-27 02:22 UTC, muicoder commented
`Error response from daemon: manifest for rancher/mirrored-library-traefik:2.11.16 not found: manifest unknown: manifest unknown`
Please try again after the image is updated.

2025-01-07 16:51 UTC, dereknola commented
You can't update to v2.11.17 when it doesn't exist yet in our mirrored repos. I just got v2.11.16 in yesterday.

2025-01-07 22:42 UTC, brandond commented
v2.11.17 is now mirrored.

2025-01-07 22:42 UTC, brandond approved these changes

2025-01-07 22:47 UTC, cwayne18 approved these changes

2025-01-07 22:52 UTC, merged