Update validate message.
k3s-io/k3s pull request #2405
Opened 2020-10-19 11:08 UTC by CzBiX

Remove unnecessary config tips.

Signed-off-by: VRan Liu <i@czbix.com>

#### Proposed Changes ####

Remove `cgroup_memory` config tips.

#### Types of Changes ####

Refine

#### Verification ####

`cgroup_memory=1` was used in the first commit changes, very soon it refined to `cgroup_enable=memory`.
And `cgroup_memory=1` removed in `v4.14`(which in Raspbian 9 Stretch).

See https://github.com/raspberrypi/linux/commit/a57f17a14ad1a2aceb5a1459d988ed71f5024999 and https://github.com/raspberrypi/linux/commit/90668092721aeb7976c5adb9b72bd35bf1e683c4

2020-10-19 18:19 UTC, brandond requested changes

2020-10-19 18:19 UTC, brandond commented on pkg/agent/run.go
> +		msg := "Failed to find memory cgroup, you may need to add \"cgroup_enable=memory\" to your linux cmdline (/boot/cmdline.txt on a Raspberry Pi)"
Note that 'F' or 'f' is prepended to this below so that it's capitalized properly for both log and error use.

2020-10-21 09:30 UTC, brandond commented
LGTM but needs `--signoff`

2021-08-05 21:30 UTC, dereknola commented
Closing this PR as this line has been moved into [pkg/cgroups/cgroups_linux.go](https://github.com/k3s-io/k3s/blob/7345ac35ae08bc74ef20f2f71d3cffbc1e01e694/pkg/cgroups/cgroups_linux.go)

2021-08-05 21:30 UTC, closed without merging