install.sh: support install on Flatcar with no args
k3s-io/k3s pull request #2551
Opened 2020-11-18 22:01 UTC by vbatts

#### Proposed Changes ####

a couple of tests for the k3s installer to enable flatcar install with fewer (no) parameters.

#### Types of Changes ####

checks inside the installer

#### Verification ####

on a Flatcar host: `bash ./install.sh`

#### Linked Issues ####

#### Further Comments ####

one thing this does not address yet is the `/usr/libexec/kubernetes` path for plugins. 
As an example, a user can make an overlay mount before running the k3s installer: https://gist.github.com/vbatts/705c2542df39495319c8601c01b658e8#file-cloud-config-yaml-L17
But this seems a bit in the weeds for this installer to do, unless the maintainers say so, and then I'll add this. Because it's just a `mkdir` and a systemd unit

2020-11-18 22:03 UTC, vbatts commented
well, it seems on v1.19.3+k3s3 the /usr/libexec/kubernetes path is no longer causing an issue.
```shell
flatcar-local ~ # sh /tmp/k3s.sh 
[INFO]  Finding release for channel stable
[INFO]  Using v1.19.3+k3s3 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.19.3+k3s3/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v1.19.3+k3s3/k3s
[INFO]  Verifying binary download
[INFO]  Installing k3s to /opt/bin/k3s
[WARN]  Failed to find the k3s-selinux policy, please install:
    yum install -y container-selinux selinux-policy-base
    yum install -y https://rpm.rancher.io/k3s/stable/common/centos/7/noarch/k3s-selinux-0.2-1.el7_8.noarch.rpm

[INFO]  Creating /opt/bin/kubectl symlink to k3s
[INFO]  Creating /opt/bin/crictl symlink to k3s
[INFO]  Skipping /opt/bin/ctr symlink to k3s, command exists in PATH at /usr/bin/ctr
[INFO]  Creating killall script /opt/bin/k3s-killall.sh
[INFO]  Creating uninstall script /opt/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s
flatcar-local ~ # kubectl get po -A
NAMESPACE     NAME                                     READY   STATUS      RESTARTS   AGE
kube-system   metrics-server-7b4f8b595-hgnxj           1/1     Running     0          6m46s
kube-system   coredns-66c464876b-nrchj                 1/1     Running     0          6m46s
kube-system   local-path-provisioner-7ff9579c6-8vxbv   1/1     Running     0          6m46s
kube-system   helm-install-traefik-rqkg4               0/1     Completed   0          6m46s
kube-system   svclb-traefik-l9gkx                      2/2     Running     0          6m35s
kube-system   traefik-5dd496474-498ps                  1/1     Running     0          6m35s
flatcar-local ~ # kubectl get no
NAME                     STATUS   ROLES    AGE     VERSION
flatcar-local.test.lan   Ready    master   7m37s   v1.19.3+k3s3
```

2020-11-20 18:43 UTC, alexellis commented
Related: https://github.com/alexellis/k3sup/issues/274 - would be nicer if we didn't have to bubble up extra vars in k3sup.

2020-12-04 07:47 UTC, joakimr-axis commented on install.sh
> +    if [ "$INSTALL_K3S_SELINUX_WARN" = true ] || grep -q "ID=flatcar" /etc/os-release; then
No expansion is being done, hence better use single quotes:

`'ID=flatcar'`

2020-12-04 07:48 UTC, joakimr-axis commented on install.sh
> +        # --- use /usr/local/bin if we can right to it, otherwise try /opt
Typo?
_if we can **right** to it_ -> _if we can **write** to it_

2020-12-04 07:53 UTC, joakimr-axis commented on install.sh
> +        touch ${BIN_DIR}/k3s-ro-test 2>/dev/null ||:
These 6 lines (229–234) can be simplified to a oneliner:

`touch ${BIN_DIR}/k3s-ro-test 2>/dev/null && rm -rf ${BIN_DIR}/k3s-ro-test || BIN_DIR=/opt/bin`

2020-12-04 12:29 UTC, vbatts commented
thanks for the review. Updated and rebased. PTAL

2020-12-04 12:34 UTC, joakimr-axis commented
> thanks for the review. Updated and rebased. PTAL

Looks very nice to me now!

2020-12-04 23:49 UTC, brandond requested changes

2020-12-04 23:49 UTC, brandond commented on install.sh
> +	touch ${BIN_DIR}/k3s-ro-test 2>/dev/null && rm -rf ${BIN_DIR}/k3s-ro-test || BIN_DIR=/opt/bin
Insufficient indentation
```suggestion
	  touch ${BIN_DIR}/k3s-ro-test 2>/dev/null && rm -rf ${BIN_DIR}/k3s-ro-test || BIN_DIR=/opt/bin
```

2020-12-05 00:36 UTC, vbatts commented
Oh beans I'll need to rebase and sign that

2020-12-05 00:45 UTC, dweomer approved these changes

2020-12-05 01:45 UTC, vbatts commented
rebased and added the missing DCO

2020-12-05 02:16 UTC, brandond approved these changes

2020-12-05 02:19 UTC, merged