Fix typo
k3s-io/k3s pull request #2739
Opened 2020-12-22 01:21 UTC by c3y1huang

#### Proposed Changes ####

Fix typo.

#### Types of Changes ####

Document

#### Verification ####

`none`

#### Linked Issues ####

`none`

#### Further Comments ####

`none`

2020-12-22 01:22 UTC, brandond approved these changes

2020-12-22 03:52 UTC, brandond requested changes
Vendored is the correct term to use for modules that we have pulled into the vendor directory. See:
https://golang.org/ref/mod#vendoring

>go mod vendor also creates the file vendor/modules.txt that contains a list of vendored packages and the module versions they were copied from. When vendoring is enabled, this manifest is used as a source of module version information, as reported by go list -m and go version -m.

2020-12-22 03:59 UTC, c3y1huang commented
> Vendored is the correct term to use for modules that we have pulled into the vendor directory. See:
> https://golang.org/ref/mod#vendoring
> 
> > go mod vendor also creates the file vendor/modules.txt that contains a list of vendored packages and the module versions they were copied from. When vendoring is enabled, this manifest is used as a source of module version information, as reported by go list -m and go version -m.

Thanks, corrected.

2020-12-22 06:19 UTC, brandond approved these changes

2021-01-20 20:13 UTC, briandowns approved these changes

2021-01-20 20:24 UTC, merged