Copied/Merged kubeconfig to $HOME/.kube/config
k3s-io/k3s pull request #2761
Opened 2020-12-30 04:48 UTC by jenting

#### Proposed Changes ####

- If $HOME/.kube/config exists, merge the kubeconfigs to $HOME/.kube/config
- Otherwise, copy the kubeconfig to $HOME/.kube/config

#### Types of Changes ####

- No modifies on kubectl command (also no message on suggesting the user start k3s server with --write-kubeconfig-mode)
- Create a merged/copied kubeconfig to $HOME/.kube/config

#### Verification ####

1. Without existing $HOME/.kube/config
- Start the k3s server
- Check /etc/rancher/k3s/k3s.yaml and $HOME/.kube/config exist
- Check the kubectl prefer kubeconfig file should be $HOME/.kube/config
   ```
   kubectl config view -v=6
   ```

2. With existing $HOME/.kube/config
- Start the KIND server
- Start the k3s server
- Check /etc/rancher/k3s/k3s.yaml exist
- Check $HOME/.kube/config exist and both KIND and k3s server information exist
- Check the kubectl prefer kubeconfig file should be $HOME/.kube/config
   ```
   kubectl config get-clusters -v=6
   ```

#### Linked Issues ####

#1541 

#### Further Comments ####

2020-12-30 14:35 UTC, erikwilson commented
Often people will run k3s as root but run kubectl as a user.
Does this change handle that situation well?

2020-12-30 14:58 UTC, jenting commented
> Often people will run k3s as root but run kubectl as a user.

> Does this change handle that situation well?

No.

Start the k3s server as root, the kubeconfig writes to /root/.kube/config. But as the normal user, the expected kubeconfig be $HOME/.kube/config.

I haven't think a good way to tackle this scenario.

2021-01-11 23:22 UTC, brandond commented
We talked this over and would prefer to reduce the scope of this:
* For this change, ONLY fix the logic at https://github.com/k3s-io/k3s/blob/master/pkg/kubectl/main.go#L18. Move `checkReadConfigPermissions` up, and change it so that if the file exists but is unreadable, we print the warning but do not set the KUBECONFIG environment variable. This should allow users with an existing ~/.kube/config to continue to use that file even if there is an unreadable /etc/rancher/k3s/k3s.yaml
* Open a separate PR to the install script to add output containing a command that they can run to merge the config at /etc/rancher/k3s/k3s.yaml into ~/.kube/config

2021-01-11 23:29 UTC, brandond requested changes
We talked this over and would prefer to reduce the scope of this:
* For this change, ONLY fix the logic at https://github.com/k3s-io/k3s/blob/master/pkg/kubectl/main.go#L18. Move `checkReadConfigPermissions` up, and change it so that if the file exists but is unreadable, we print the warning but do not set the KUBECONFIG environment variable. This should allow users with an existing ~/.kube/config to continue to use that file even if there is an unreadable /etc/rancher/k3s/k3s.yaml
* Open a separate PR to the install script to add output containing a command that they can run to copy the config at /etc/rancher/k3s/k3s.yaml into ~/.kube/config (for example, `sudo /usr/local/bin/kubectl config view --raw | tee ~/.kube/config`)

2021-07-17 04:44 UTC, closed without merging