change etcd dir permission if it exists
k3s-io/k3s pull request #2784
Opened 2021-01-07 20:00 UTC by MonzElmasry

#### Proposed Changes ####

change the permission of etcd dir if it exists after upgrades

#### Verification ####
```
sudo ls -ld /var/lib/rancher/k3s/server/db/etcd
drwxr-xr-x 3 root root 4096 Nov 12 20:08 /var/lib/rancher/k3s/server/db/etcd
```

2021-01-07 20:19 UTC, galal-hussein approved these changes
LGTM

2021-01-07 20:26 UTC, briandowns approved these changes

2021-01-07 20:26 UTC, brandond requested changes

2021-01-07 20:26 UTC, brandond commented on pkg/etcd/etcd.go
> +		}
err return appears to be unused - need either return err if non-nil, or check for nil error before looking at info.
```suggestion
		if info, err := os.Stat(etcdDBDir(e.config)); err == nil && info.Mode().Perm() != 0700 {
			os.Chmod(info.Name(), 0700)
		}
```

2021-01-08 21:43 UTC, brandond approved these changes

2021-01-08 21:48 UTC, briandowns approved these changes

2021-01-08 22:45 UTC, merged