wip - Traefik v2 integration
k3s-io/k3s pull request #2910
Opened 2021-02-08 22:05 UTC by erikwilson

#### Proposed Changes ####
Happy path Traefik v2 integration, modified from #2774

#### Types of Changes ####
Skip Traefik v2 if Traefik v1 is present
Combine manifests (still deploys 2 helm charts)

#### Verification ####
k8s 1.20.2 -> this PR

#### Linked Issues ####

#### Further Comments ####
Due to the annotation -> crd nature of Traefik v1 -> v2 we can not upgrade, needs manual migration (see https://github.com/traefik/traefik-migration-tool)

2021-02-18 19:07 UTC, dweomer approved these changes

2021-02-19 10:54 UTC, brandond requested changes

2021-02-19 10:54 UTC, brandond commented on pkg/server/server.go
> +		logrus.WithError(err).Info("Not find traefik")
Should we always log a message if the chart can't be found? Or just if it's an error? Either way we should probably use correct grammar.
```suggestion
		logrus.WithError(err).Info("Failed to get existing traefik HelmChart")
```

2021-02-19 10:54 UTC, brandond commented on pkg/server/server.go
> +// isHelmChartTraefikV1 checks the chart with "traefik-1." prefix.
```suggestion
// isHelmChartTraefikV1 checks for an existing HelmChart resource with spec.chart containing traefik-1,
// as deployed by the legacy chart (https://%{KUBERNETES_API}%/static/charts/traefik-1.81.0.tgz)
```

2021-02-19 10:54 UTC, brandond commented on pkg/server/server.go
> +		logrus.WithField("chart", chart).Info("Found traefik v1 running")
```suggestion
		logrus.WithField("chart", chart).Info("Found existing traefik v1 HelmChart")
```

2021-02-24 17:59 UTC, brandond approved these changes

2021-03-01 22:18 UTC, merged