expand CRD acronym in readme
k3s-io/k3s pull request #3216
Opened 2021-04-18 15:24 UTC by bionicles

had to look this up. save the next guy a google search

#### Proposed Changes ####

#### Types of Changes ####

#### Verification ####

#### Linked Issues ####

#### Further Comments ####

2021-04-18 19:36 UTC, brandond requested changes

2021-04-18 19:36 UTC, brandond commented on README.md
> +* [Helm-controller](https://github.com/k3s-io/helm-controller) to allow Customer Resource Definition (CRD) driven deployment of helm manifests
```suggestion
* [Helm-controller](https://github.com/k3s-io/helm-controller) to allow Custom Resource Definition (CRD) driven deployment of helm manifests
```

2021-04-23 17:24 UTC, brandond commented
LGTM, the commit needs to be signed for DCO though.

2021-04-26 15:33 UTC, bionicles commented
i followed the instructions on sign-off and didn't work. ill just let you go ahead and fix it yourself, it's a minor copy-paste onto the readme

2021-04-26 15:33 UTC, closed without merging