retry on creating etcd proxy
k3s-io/k3s pull request #3225
Opened 2021-04-23 16:27 UTC by galal-hussein

Signed-off-by: galal-hussein <hussein.galal.ahmed.11@gmail.com>

#### Proposed Changes ####

retry on creating etcd proxy load balancer, to avoid errors in rke2 when etcd is disabled after being enabled

#### Types of Changes ####

bug fix

#### Linked Issues ####

https://github.com/rancher/rke2/issues/886

2021-04-23 16:53 UTC, brandond requested changes

2021-04-23 16:53 UTC, brandond commented on pkg/cluster/cluster.go
> +				logrus.Warnf("failed to setup etcd proxy: %v", err)
```suggestion
				logrus.Warnf("Failed to setup etcd proxy: %v - retrying", err)
```

2021-04-23 16:53 UTC, brandond commented on pkg/cluster/cluster.go
> +			if err != nil {
Do we want to only retry on specific errors, such as the port already being in use? Are there other things that might cause this to fail, or is that pretty much it?

2021-04-23 17:58 UTC, briandowns approved these changes
LGTM

2021-04-29 19:32 UTC, brandond approved these changes

2021-04-29 20:11 UTC, merged