Fail to start k3s if nm-cloud-setup is enabled
k3s-io/k3s pull request #3465
Opened 2021-06-16 09:43 UTC by manuelbuil

Signed-off-by: Manuel Buil <mbuil@suse.com>

#### Proposed Changes ####
Even though we are documenting that nm-cloud-setup service breaks the k3s cluster: rancher/docs#3336, it is a good idea to verify this when starting the k3s service and not allow it to start if the user forgot to disable that service

#### Types of Changes ####
New Feature. Verifies if nm-cloud-setup is enabled

#### Verification ####
Deploy RHEL8.4 which use nm-cloud-setup by default and run k3s. It should fail to start with the following log in journactl:
```
116635:Jun 16 09:41:03 ip-10-0-10-13.eu-west-3.compute.internal bash[1118717]: + /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
116636-Jun 16 09:41:03 ip-10-0-10-13.eu-west-3.compute.internal bash[1118717]: + exit 1
```

#### Linked Issues ####
rancher/rke2#1053

2021-06-16 13:18 UTC, Oats87 reviewed
Do we need to worry about the `nm-cloud-setup.timer` service as well?

2021-06-16 14:01 UTC, manuelbuil commented
> Do we need to worry about the `nm-cloud-setup.timer` service as well?

My tests show that if `nm-cloud-setup.service` is disabled, that is enough

2021-06-16 18:23 UTC, brandond requested changes

2021-06-16 18:23 UTC, brandond commented on install.sh
> +ExecStartPre=/bin/sh -xc '/usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service && exit 1 || exit 0'
```suggestion
ExecStartPre=/bin/sh -xc '! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service'
```

2021-06-16 18:23 UTC, brandond commented on k3s.service
> +ExecStartPre=/bin/sh -xc '/usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service && exit 1 || exit 0'
```suggestion
ExecStartPre=/bin/sh -xc '! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service'
```

2021-06-16 18:23 UTC, brandond commented on package/rpm/install.sh
> +ExecStartPre=/bin/sh -xc '/usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service && exit 1 || exit 0'
```suggestion
ExecStartPre=/bin/sh -xc '! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service'
```

2021-06-17 10:25 UTC, manuelbuil commented on install.sh
> +ExecStartPre=/bin/sh -xc '/usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service && exit 1 || exit 0'
Great idea Brad!

2021-06-17 10:37 UTC, brandond approved these changes

2021-06-18 09:37 UTC, merged