[release-1.20] - Backport K3s/RKE2 bootstrap data is encrypted with empty string if user does not supply a token
k3s-io/k3s pull request #3516
Opened 2021-06-25 19:24 UTC by galal-hussein

* Fix storing bootstrap data with empty token string

Signed-off-by: galal-hussein <hussein.galal.ahmed.11@gmail.com>

* delete node password secret after restoration

fixes to bootstrap key

vendor update

Signed-off-by: galal-hussein <hussein.galal.ahmed.11@gmail.com>

* fix comment

Signed-off-by: galal-hussein <hussein.galal.ahmed.11@gmail.com>

* fix typo

Signed-off-by: galal-hussein <hussein.galal.ahmed.11@gmail.com>

* more fixes

Signed-off-by: galal-hussein <hussein.galal.ahmed.11@gmail.com>

* fixes

Signed-off-by: galal-hussein <hussein.galal.ahmed.11@gmail.com>

* fixes

Signed-off-by: galal-hussein <hussein.galal.ahmed.11@gmail.com>

* typos

Signed-off-by: galal-hussein <hussein.galal.ahmed.11@gmail.com>

* Removing dynamic listener file after restoration

Signed-off-by: galal-hussein <hussein.galal.ahmed.11@gmail.com>

* go mod tidy

Signed-off-by: galal-hussein <hussein.galal.ahmed.11@gmail.com>

#### Proposed Changes ####

#### Types of Changes ####

#### Verification ####

#### Linked Issues ####

https://github.com/rancherlabs/rancher-security/issues/832

#### Further Comments ####

2021-06-29 20:37 UTC, brandond commented
Will need https://github.com/k3s-io/k3s/pull/3514 rolled in as well.

2021-06-29 20:38 UTC, brandond requested changes
Will need https://github.com/k3s-io/k3s/pull/3545 rolled in as well.

2021-07-13 16:54 UTC, briandowns approved these changes

2021-07-13 17:34 UTC, brandond approved these changes

2021-07-13 17:38 UTC, brandond requested changes

2021-07-13 17:38 UTC, brandond commented on go.mod
> +	github.com/k3s-io/kine v0.6.1
Need to pull in https://github.com/k3s-io/k3s/commit/246b378a2743e659a2343b60123ba51a38dcc0ac for kine delete fix

2021-07-13 17:42 UTC, galal-hussein commented
https://github.com/k3s-io/k3s/issues/3630 adding issue for backporting updating kine to fix delete issue

2021-07-13 17:46 UTC, brandond approved these changes

2021-07-13 17:47 UTC, galal-hussein commented
https://github.com/k3s-io/k3s/issues/3631 - backport issue for empty node password file

2021-07-13 20:58 UTC, merged