Add issue template for creating release checklist issues
k3s-io/k3s pull request #3604
Opened 2021-07-09 01:00 UTC by cwayne18

Signed-off-by: cwayne18 <cwayne@ubuntu.com>

#### Proposed Changes ####

Adds an issue template for ensuring release checklist issues are formatted properly

#### Types of Changes ####

New issue template

#### Verification ####

Additional issue template when creating a new issue

#### Linked Issues ####

#### User-Facing Change ####

#### Further Comments ####

2021-07-09 01:19 UTC, brandond approved these changes

2021-07-09 03:56 UTC, briandowns approved these changes

2021-07-09 12:55 UTC, briandowns commented
Should we provide additional links for more detail on some of those? I think that might be helpful.

2021-07-09 12:57 UTC, cwayne18 commented
> Should we provide additional links for more detail on some of those? I think that might be helpful.

We certainly could! This was just a copy from the most recent "cut release" issue so it's the current process. That said, I'm definitely not against enhancing it, do you have any specific suggestions to add?

2021-07-09 13:08 UTC, cwayne18 commented
To see what this will look like, you can see: https://github.com/cwayne18/k3s/issues/new/choose

2021-07-09 15:21 UTC, davidnuzik requested changes
Requesting couple small changes.

2021-07-09 15:21 UTC, davidnuzik commented on .github/ISSUE_TEMPLATE/cut_release.md
> +- [ ] PM: Dev and QA team to be notified of the incoming releases - send calendar invite
Nit:
```suggestion
- [ ] PM: Dev and QA team to be notified of the incoming releases - add event to team calendar
```

2021-07-09 15:21 UTC, davidnuzik commented on .github/ISSUE_TEMPLATE/cut_release.md
> +- [ ] PM: Dev and QA team to be notified of the date we will mark the latest release as stable - send calendar invite
Two things below.

Nit:
```suggestion
- [ ] PM: Dev and QA team to be notified of the date we will mark the latest release as stable - add event to team calendar
```

Note:
Only the latest minor release would have this checklist item (e.g. 1.21.x currently). So, do we need to qualify this or something? Basically this checklist item does not apply to older minor release branches like 1.19 and 1.20 today.

2021-07-09 15:53 UTC, davidnuzik approved these changes
LGTM, can we squash and merge?

2021-07-09 18:33 UTC, galal-hussein approved these changes

2021-07-15 13:39 UTC, fapatel1 approved these changes
LGTM

2021-07-15 13:44 UTC, merged