Add checkbox to denote backporting required on issue templates
k3s-io/k3s pull request #3669
Opened 2021-07-19 21:18 UTC by cwayne18

Signed-off-by: Chris Wayne <cwayne18@gmail.com>

#### Proposed Changes ####

Add a checkbox to issue templates letting us know that backports are needed.  This theoretically could help with automating opening backport issues.

#### Types of Changes ####

Issue template changes

#### Verification ####

Verify checkbox exists when creating a new issue

#### Linked Issues ####

#### User-Facing Change ####

```release-note
NONE
```

#### Further Comments ####

2021-07-19 21:52 UTC, brandond requested changes

2021-07-19 21:52 UTC, brandond commented on .github/ISSUE_TEMPLATE/bug_report.md
> +Does this PR need to be backported to older releases?  If so, please check this box to ensure no necessary backports are missed."
```suggestion
Does this fix need to be backported to older releases?  If so, please check this box and list the branches it should be backported to.
```

2021-07-19 21:52 UTC, brandond commented on .github/ISSUE_TEMPLATE/feature_request.md
> +Does this PR need to be backported to older releases?  If so, please check this box to ensure no necessary backports are missed."
```suggestion
Does this fix need to be backported to older releases?  If so, please check this box and list the branches it should be backported to.
```

2021-07-19 22:36 UTC, brandond approved these changes

2021-07-20 17:09 UTC, briandowns approved these changes

2021-07-23 16:07 UTC, merged