install.sh: Use built-in shell functionality instead of awk
k3s-io/k3s pull request #3738
Opened 2021-07-30 13:45 UTC by joakimr-axis

#### Proposed Changes ####

If `install.sh` relies on `awk`, `install.sh` malfunctions when run on a device with a limited environment where `awk` is not available. This patch replaces the use of `awk` (in the killall script created by `install.sh`) with built-in shell script functionality.

#### Types of Changes ####
Bugfix

#### Verification ####
Run the killall script on a machine that does not have awk installed.

#### Linked Issues ####
https://github.com/k3s-io/k3s/issues/3737

#### User-Facing Change ####

```release-note
NONE
```

#### Further Comments ####

2021-07-30 13:47 UTC, joakimr-axis commented
Ping @brandond for review.

2021-07-30 16:56 UTC, dweomer approved these changes

2021-07-30 16:57 UTC, briandowns approved these changes

2021-07-30 17:30 UTC, brandond commented
Can you ensure that this doesn't regress either of the issues that were fixed in #2229:
* #2120
* #2211

2021-07-30 20:00 UTC, joakimr-axis commented
> Can you ensure that this doesn't regress either of the issues that were fixed in #2229:
> 
> * [uninstall script fails with /bin/umount: Argument list too long #2120](https://github.com/k3s-io/k3s/issues/2120)
> * [k3s-killall.sh fails to unmount where /bin/sh is dash #2211](https://github.com/k3s-io/k3s/issues/2211)

Good that you mention this. Yes, the changes are fully POSIX-only and are tested with precisely dash.
And regarding the argument list: what is piped out from `sort -r` here is identical to the `awk` command when I tried this on my test machine with k3s installed (and the mounts involved there).

2021-08-03 23:57 UTC, brandond requested changes

2021-08-03 23:57 UTC, brandond commented on install.sh
> +    while read -r _ path _; do
can you wrap this in a `$({ set +x; } 2>/dev/null;   set -x;)` as seen above? The use of a shell loop to filter the paths results in running this uninstall script filling the terminal with:
```console
+ read -r _ path _
+ case "$path" in
+ read -r _ path _
+ case "$path" in
+ read -r _ path _
+ case "$path" in
+ read -r _ path _
+ case "$path" in
+ read -r _ path _
```

2021-08-04 19:06 UTC, brandond approved these changes

2021-08-04 19:06 UTC, merged