Fix initial start of etcd only nodes
k3s-io/k3s pull request #3748
Opened 2021-08-02 23:15 UTC by galal-hussein

Signed-off-by: galal-hussein <hussein.galal.ahmed.11@gmail.com>

#### Proposed Changes ####
Fix initial start of systemd notify of etcd only nodes

#### Types of Changes ####
bug fix

#### Linked Issues ####
https://github.com/rancher/rke2/issues/1483

2021-08-02 23:58 UTC, brandond commented
Can you try this instead:
* Don't revert the change to `pkg/cli/server/server.go`
* Instead of adding the immediate READY notification if `cfg.ETCDAgent` is set in `pkg/agent/run.go`, after `setupTunnelAndRunAgent` returns, if `cfg.ETCDAgent` is set then reset the variable by calling `os.Setenv("NOTIFY_SOCKET", notifySocket)`. Down at the bottom make the `os.Setenv` and `systemd.SdNotify` calls conditional on `!cfg.ETCDAgent`.

This should have a net effect of resetting the environment variable so that the server goroutine can send the notification when etcd becomes ready (on etcd-only servers), and preventing the agent from sending a second extra notification later when the apiserver comes up.

2021-08-02 23:59 UTC, brandond requested changes
^^

2021-08-03 17:46 UTC, brandond approved these changes

2021-08-03 17:52 UTC, briandowns approved these changes

2021-08-03 17:53 UTC, merged