[backport 1.22] tests/vagrant
k3s-io/k3s pull request #4499
Opened 2021-11-15 22:59 UTC by dweomer

From https://github.com/k3s-io/k3s/commit/c77efe64e1521d48c91987b92f406d616fe964eb:
- workflow: cgroup2 :arrow_right: cgroup
- tests/cgroup2/ :arrow_right: tests/vagrant/cgroup/unified/fedora-34/

Signed-off-by: Jacob Blain Christen <jacob@rancher.com>

2021-11-15 23:25 UTC, dereknola requested changes

2021-11-15 23:25 UTC, dereknola commented on tests/TESTING.md
> +See the [local storage test](https://github.com/k3s-io/k3s/blob/master/tests/integration/localstorage/localstorage_int_test.go) as a package agnostic example.
At the time I wrote this, I didn't realize that you could use "relative" links. 
```suggestion
See the [local storage test](./integration/localstorage/local_storage_int_test.go) as a package agnostic example.
```

2021-11-15 23:44 UTC, dereknola approved these changes

2021-11-15 23:46 UTC, dereknola requested changes

2021-11-15 23:46 UTC, dereknola commented on tests/TESTING.md
> +See the [local storage test](../tests/integration/localstorage/local_storage_int_test.go) as a package agnostic example.
My bad, I gave a bad suggestion.
```suggestion
See the [local storage test](../tests/integration/localstorage/localstorage_int_test.go) as a package agnostic example.
```

2021-11-15 23:50 UTC, dereknola approved these changes

2021-11-16 21:20 UTC, dweomer commented
It would seem that I failed to back-port BTRFS support to 1.22

2021-11-17 23:30 UTC, merged