Add k3s etcd restoration test
k3s-io/k3s pull request #5014
Opened 2022-01-24 22:07 UTC by galal-hussein

Signed-off-by: galal-hussein <hussein.galal.ahmed.11@gmail.com>

#### Proposed Changes ####

Adding k3s snapshot restoration integration test

2022-01-25 15:53 UTC, briandowns commented on tests/util/unit.go
> +func FindFile(root, findStr string) (string, error) {
```suggestion
func FindFile(root, filename string) (string, error) {
```

2022-01-25 15:54 UTC, briandowns commented on tests/util/integration.go
> +	fmt.Println("cmd args: %#v", cmdArgs)
Where these fmt lines intended or debug?

2022-01-28 21:05 UTC, dereknola requested changes

2022-01-28 21:05 UTC, dereknola commented on tests/util/integration.go
> +	time.Sleep(10 * time.Second)
There should be a need to sleep when running bash commands
```suggestion
```

2022-02-07 22:31 UTC, dereknola requested changes

2022-02-07 22:31 UTC, dereknola commented on pkg/etcd/int_tests/restore/etcd_restore_int_test.go
> +			// Expect(out).To()
Did you still need these?

2022-02-07 22:31 UTC, dereknola commented on tests/util/unit.go
> +func FindFile(root, filename string) (string, error) {
It doesn't look like this is being used anywhere, do we still need it?

2022-02-07 22:36 UTC, briandowns approved these changes

2022-02-07 22:40 UTC, dereknola approved these changes

2022-02-08 19:24 UTC, merged