Add Rocket.Chat to list of adopters
k3s-io/k3s pull request #5017
Opened 2022-01-25 03:05 UTC by geekgonecrazy

#### Proposed Changes ####

Add Rocket.Chat to list of adopters.  We utilize k3s under our services including our SaaS offering

#### Types of Changes ####

Doc update

#### Verification ####

#### Linked Issues ####

#### User-Facing Change ####

```release-note

```

#### Further Comments ####

2022-01-25 03:24 UTC, brandond requested changes
Thanks for the addition! Please sign your commit so that the DCO check passes!

2022-01-25 15:44 UTC, briandowns approved these changes
LGTM

2022-01-25 20:39 UTC, geekgonecrazy commented
@brandond done 👍

2022-01-25 20:50 UTC, brandond approved these changes

2022-01-26 17:55 UTC, cwayne18 commented
Thanks so much for this!

2022-01-26 17:55 UTC, merged