Add wireguard native flannel backend
k3s-io/k3s pull request #5391
Opened 2022-04-06 08:23 UTC by rbrtbnfgl

#### Proposed Changes ####

Added native-wireguard flannel backend to use the wireguard backend included in flannel.
The older wireguard backend will remain as it is for backward compatibility (#5011)

#### Types of Changes ####

New Feature

#### Verification ####

Use the option `--flannel-backend=native-wireguard` to set up a cluster that uses wireguard as backend
On the node `flannel-wg` interface should be there and in case of dual-stack `flannel-wg-v6`

#### Linked Issues ####

 #4364 #5216

#### User-Facing Change ####

```release-note

```

#### Further Comments ####

2022-04-06 16:48 UTC, dereknola approved these changes

2022-04-06 17:27 UTC, manuelbuil commented
Great! Could you add a log stating that wireguard will be deprecated if config.FlannelBackendWireguard is chosen? Something like: "The wireguard backend is deprecated and will be removed in k3s v1.26, please switch to native-wireguard. Check our docs for information about how to migrate"

2022-04-06 23:14 UTC, brandond requested changes
LGTM, but lets be consistent about calling it 'wireguard-native' not 'native wireguard' just so the bits all line up lexicographically.

2022-04-06 23:14 UTC, brandond commented on pkg/daemons/config/types.go
> +	FlannelBackendNativeWireguard = "native-wireguard"
```suggestion
	FlannelBackendWireguardNative = "wireguard-native"
```

2022-04-06 23:14 UTC, brandond commented on pkg/agent/flannel/setup.go
> +	case config.FlannelBackendNativeWireguard:
```suggestion
	case config.FlannelBackendWireguardNative:
```

2022-04-07 09:58 UTC, manuelbuil commented
One extra thing! Please update https://github.com/k3s-io/k3s/blob/master/pkg/cli/cmds/server.go#L207 and add the new option. In the old option, please add `(deprecated)` after it

2022-04-07 15:01 UTC, manuelbuil approved these changes

2022-04-07 16:11 UTC, brandond approved these changes

2022-04-08 07:13 UTC, merged

2022-06-20 12:23 UTC, ChristianCiach commented
Please don't forget about the documentation. 

I am currently experimenting with v1.24.1+k3s1, which, as expected, logs this on startup:

```
The wireguard backend is deprecated and will be removed in k3s v1.26, please switch to wireguard-native. Check our docs for information about how to migrate
```
Unfortunately there is no documentation about this backend at all, especially no documentation about the migration.

According to https://github.com/k3s-io/k3s/pull/5011 a reboot of the node or manualy deletion of the flannel device should fix this.