Add certificate rotation integration tests
k3s-io/k3s pull request #5393
Opened 2022-04-06 21:47 UTC by galal-hussein

#### Proposed Changes ####

#### Types of Changes ####

#### Verification ####

#### Linked Issues ####

#### User-Facing Change ####

```release-note

```

#### Further Comments ####

2022-04-06 22:34 UTC, dereknola requested changes

2022-04-06 22:34 UTC, dereknola commented on tests/integration/certrotation/certrotation_int_test.go
> +	RunSpecs(t, "Etcd Snapshot Suite")
```suggestion
func Test_IntegrationCertRotation(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "Cert Rotation Suite")
```

2022-04-06 22:34 UTC, dereknola commented on tests/integration/certrotation/certrotation_int_test.go
> +package snapshot_test
```suggestion
package cert_rotation_test
```

2022-04-07 17:19 UTC, galal-hussein commented on tests/integration/certrotation/certrotation_int_test.go
> +package snapshot_test
will fix

2022-04-07 17:20 UTC, briandowns commented on tests/integration/certrotation/certrotation_int_test.go
> +var tmpdDataDir = "/tmp/certrotationtest"
```suggestion
const tmpdDataDir = "/tmp/certrotationtest"
```

2022-04-08 16:35 UTC, dereknola approved these changes

2022-04-08 18:03 UTC, briandowns approved these changes

2022-04-08 18:03 UTC, merged