Restore `--docker` flag backed by embedded cri-dockerd
k3s-io/k3s pull request #5916
Opened 2022-07-28 20:31 UTC by brandond

#### Proposed Changes ####

Restore `--docker` flag backed by embedded cri-dockerd

#### Types of Changes ####

enhancement

#### Verification ####

See linked issue

#### Testing ####

TBD

#### Linked Issues ####

* https://github.com/k3s-io/k3s/issues/5741

#### User-Facing Change ####
```release-note
The `--docker` flag has been restored to k3s, as a shortcut to enabling embedded cri-dockerd
```

#### Further Comments ####

2022-07-29 16:30 UTC, dereknola requested changes
Please add an integration test for this flag. The [startup test](https://github.com/k3s-io/k3s/blob/master/tests/integration/startup/startup_int_test.go) should be fine for this.

2022-07-29 16:42 UTC, brandond commented
Yeah, I need to add an ADR and tests. Kinda interesting that we never had even a basic cluster startup yes for docker support...

2022-07-29 22:13 UTC, dereknola approved these changes

2022-08-05 07:05 UTC, rbrtbnfgl approved these changes

2022-08-05 09:39 UTC, merged