Fix dualStack test and change ipv6 network prefix
k3s-io/k3s pull request #6023
Opened 2022-08-22 15:53 UTC by manuelbuil

Signed-off-by: Manuel Buil <mbuil@suse.com>

#### Proposed Changes ####

2 changes:

1. Add "kubelet-arg: "--node-ip=0.0.0.0" " which is a temporary workaround to avoid the current bug in upstream kubernetes: https://github.com/kubernetes/kubernetes/issues/111695
2. Change the ipv6 network prefix, which in my opinion, it is wrong. According to the RFCs, private ipv6 addresses must start with fc or fd. Public ipv6 addresses must start with 2001 ==> https://en.wikipedia.org/wiki/Reserved_IP_addresses#IPv6. Ipv6 addresses starting with `a11` is not complying with the standard. However, I wonder why linux does not complain about this :thinking: 

#### Types of Changes ####

Bugfix

#### Verification ####

Deploy the dualStack test without disabling network policies

#### Testing ####

#### Linked Issues ####

#### User-Facing Change ####

```release-note

```

#### Further Comments ####

2022-08-22 16:39 UTC, dereknola requested changes
Nit: helps for later removal

2022-08-22 16:39 UTC, dereknola commented on tests/e2e/dualstack/Vagrantfile
> +        kubelet-arg: "--node-ip=0.0.0.0"
```suggestion
        kubelet-arg: "--node-ip=0.0.0.0" # Workaround for https://github.com/kubernetes/kubernetes/issues/111695
```

2022-08-22 17:15 UTC, dereknola approved these changes

2022-08-22 17:37 UTC, brandond approved these changes

2022-08-26 16:38 UTC, dereknola commented
Drone CI has passes, not sure why the check is marked as failing https://drone-pr.k3s.io/k3s-io/k3s/4612

2022-08-26 17:03 UTC, merged