Add cluster reset test
k3s-io/k3s pull request #6161
Opened 2022-09-20 16:13 UTC by ShylajaDevadiga

#### Proposed Changes ####
Add cluster-reset test to nightly builds. 

#### Testing ####
NA

#### Linked Issues ####
https://github.com/k3s-io/k3s/issues/6156

2022-09-20 17:40 UTC, briandowns approved these changes

2022-09-23 17:02 UTC, rancher-max requested changes

2022-09-23 17:02 UTC, rancher-max commented on tests/e2e/clusterreset/clusterreset_test.go
> +				Expect(res).Should(ContainSubstring("cluster-reset"))
Could this expect ever get false positives? I wonder if we change this to be most of that full last line from the cluster-reset command. I don't have it off the top of my head, but it's something like "cluster-reset has finished successfully. On existing nodes, please delete ${datadir]/db and rejoin"

2022-09-23 17:02 UTC, rancher-max commented on tests/e2e/clusterreset/clusterreset_test.go
> +						g.Expect(node.Status).Should(Equal("Ready"))
After the initial cluster-reset, only `server-0` should be `Ready` and other nodes should be `NotReady` after some time. I think that might be a safer check for cluster-reset functionality. Will probably have to increase the timeout of this check for that too.

2022-09-29 18:51 UTC, ShylajaDevadiga commented on tests/e2e/clusterreset/Vagrantfile
> +def getDBType(role, role_num, vm)
Default is set to etcd

2022-09-29 19:00 UTC, rancher-max approved these changes

2022-09-30 01:11 UTC, merged