Change addr types metrics server
k3s-io/k3s pull request #6386
Opened 2022-10-31 09:29 UTC by manuelbuil

#### Proposed Changes ####

Puts ExternalIP as the first parameter in the metrics-server kubelet-preferred-address-types when `flannel-external-ip` is true. This is required so that the metrics server knows how to reach the kubelet process of the nodes

#### Types of Changes ####

Bugfix

#### Verification ####

Deploy k3s and check that metrics server args are:

* `--kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname` when `flannel-external-ip=false`
* `--kubelet-preferred-address-types=ExternalIP,InternalIP,Hostname` when `flannel-external-ip=true`

Verify that `kubectl top` works correctly, i.e. shows all nodes in the cluster, when using  `flannel-external-ip=true`

#### Testing ####

#### Linked Issues ####

https://github.com/k3s-io/k3s/issues/6326

#### User-Facing Change ####

```release-note
Fix for metrics-server in the multi-cloud cluster env
```

#### Further Comments ####

2022-10-31 21:50 UTC, dereknola approved these changes

2022-10-31 21:55 UTC, brandond requested changes
Lets call it PREFERRED_ADDRESS_TYPES in case we end up wanting to use it elsewhere?

Do you think we should also use this to set the order at https://github.com/k3s-io/k3s/blob/master/pkg/daemons/control/server.go#L185

2022-10-31 21:55 UTC, brandond commented on manifests/metrics-server/metrics-server-deployment.yaml
> +        - --kubelet-preferred-address-types=%{ADDRESS_TYPES_METRICS}%
```suggestion
        - --kubelet-preferred-address-types=%{PREFERRED_ADDRESS_TYPES}%
```

2022-10-31 21:55 UTC, brandond commented on pkg/server/server.go
> +		"%{ADDRESS_TYPES_METRICS}%":       addrTypesPrioTemplate(controlConfig.FlannelExternalIP),
```suggestion
		"%{PREFERRED_ADDRESS_TYPES}%":       addrTypesPrioTemplate(controlConfig.FlannelExternalIP),
```

2022-11-03 09:18 UTC, manuelbuil reviewed
Per discussion with Brad, changes the kube-api flags too. Will only make sense in case of not using the egressSelector

2022-11-03 09:18 UTC, manuelbuil commented on manifests/metrics-server/metrics-server-deployment.yaml
> +        - --kubelet-preferred-address-types=%{ADDRESS_TYPES_METRICS}%
ok

2022-11-03 09:18 UTC, manuelbuil commented on pkg/server/server.go
> +		"%{ADDRESS_TYPES_METRICS}%":       addrTypesPrioTemplate(controlConfig.FlannelExternalIP),
ok

2022-11-04 08:57 UTC, brandond approved these changes

2022-11-04 10:11 UTC, merged