Add snapshot restore e2e test
k3s-io/k3s pull request #6396
Opened 2022-11-01 19:54 UTC by ShylajaDevadiga

#### Proposed Changes ####
Add test for snapshots and restore

#### Verification ####
go test -v -timeout=30m ./snapshotrestore_test.go --serverCount=3 --agentCount=1

#### Linked Issues ####
NA

2022-11-01 20:59 UTC, briandowns commented on tests/e2e/snapshotrestore/snapshotrestore_test.go
> +var failed = false
```suggestion
var failed bool
```

2022-11-01 22:14 UTC, brandond approved these changes

2022-11-01 22:21 UTC, dereknola requested changes

2022-11-01 22:21 UTC, dereknola commented on tests/e2e/snapshotrestore/Vagrantfile
> +RANCHER = (ENV['E2E_RANCHER'] || "")
No need to support any of these Variables for this test, this is an etcd only test that does not deploy any workloads.
So EXTERNAL_DB = "etcd" should be the only option.

2022-11-01 22:21 UTC, dereknola commented on tests/e2e/snapshotrestore/Vagrantfile
> +  end
Remove support for these variables, they are not necessary

2022-11-01 22:21 UTC, dereknola commented on tests/e2e/snapshotrestore/Vagrantfile
> +  end
See above comments

2022-11-01 22:21 UTC, dereknola commented on tests/e2e/snapshotrestore/Vagrantfile
> +end
This test requires embedded etcd, 
```suggestion
def getDBType(role, role_num, vm)
  if ( EXTERNAL_DB == "" || EXTERNAL_DB == "etcd" )
    if role.include?("server") && role_num == 0
      return "cluster-init: true"
    end
  else
    puts "Unknown EXTERNAL_DB: " + EXTERNAL_DB
    abort
  end
  return ""
end
```

2022-11-02 03:03 UTC, dereknola approved these changes

2022-11-02 03:04 UTC, dereknola commented
Merging, codespell is marking a false positive

2022-11-02 03:04 UTC, merged