skip all pipelines based on what is in the PR
k3s-io/k3s pull request #6996
Opened 2023-02-21 14:46 UTC by matttrach

#### Proposed Changes ####

This change will add a pipeline which implements [drone-skip-pipeline](https://github.com/joshdk/drone-skip-pipeline).
The purpose is to provide some mechanism to automatically skip pipelines which are not necessary due to the files that are being changed. For example, if a markdown file is the only file changed, then we don't need to run functional tests. This will reduce our integration time.

#### Types of Changes ####

No new code to k3s, all changes in .drone.yml

#### Verification ####

Unfortunately, Drone provides no way to test this outside of letting it run in your repo.

#### Linked Issues ####

This addresses #6980.

#### User-Facing Change ####
This has no user facing change.

#### Further Comments ####

There is [another plugin](https://github.com/fernandrone/drone-ignore-config) which may give us similar functionality, but is out of date and requires configuration on the drone server, I would like to try this one first to avoid the additional handoffs.
There is more than one way to implement this plugin, the way I have provided is the one with the fewest changes to existing steps, I am open to additional suggestions.

2023-02-21 22:27 UTC, brandond approved these changes

2023-02-21 22:33 UTC, briandowns approved these changes

2023-02-27 21:37 UTC, dereknola approved these changes

2023-03-02 18:29 UTC, brandond requested changes
I'm not sure what's going on with all the commits that have been added to this branch after approval; please get it back to just the single change before merging.

2023-03-02 18:43 UTC, matttrach commented
sorry, I will. I was finally able to test this and it doesn't work... :(
The plugin is only compiled on amd64, I think I will need to head back to the drawing board on this one.

2023-03-07 18:57 UTC, matttrach commented
I put everything into a single commit, I believe this is ready for review.

2023-03-07 19:00 UTC, matttrach commented on .drone.yml
> +    path: /var/run/docker.sock
the diff is unclear here, but if you look at the file I just removed some spacing here to conform to the way the rest of the yaml is written (lists have same spacing as parent)

2023-03-07 19:01 UTC, matttrach commented on README.md
> +Please do not file issues about security issues.
This is a trivial spacing change to validate that .md files are ignored.

2023-03-07 21:02 UTC, cwayne18 reviewed
This looks neat thanks! Can we add .github/*,  MAINTAINERS, CODEOWNERS to the skip list please?

2023-03-08 16:12 UTC, matttrach commented
done. Also added DCO, channel.yaml, and LICENSE (although they are unlikely to change)

2023-03-08 17:22 UTC, dereknola approved these changes
Is is possible to put all the repeated bash commands into a script file and just call that?

2023-03-08 17:31 UTC, matttrach commented
I think the special exit code has to be executed from the root scope, I can probably add a file and execute it, but it would only  reduce 1 line of code per copy.

2023-03-08 18:04 UTC, cwayne18 approved these changes

2023-03-08 18:48 UTC, brandond requested changes
Do we want this on all CI runs, or just on PR? It feels like we should never skip running CI on merges or tags - basically anything that runs on drone-publish. Should we add something to restrict this to just drone-pr?

```yaml
trigger:
  instance:
  - drone-pr.k3s.io
  ref:
  - refs/pull/*/head
```

2023-03-08 19:32 UTC, matttrach commented
Definitely don't wanna skip on tags, thanks!
I think bounding the skip to pushes and pull requests should give us a good compromise for how often.

2023-03-08 19:45 UTC, brandond approved these changes

2023-03-09 15:14 UTC, ivan-claire approved these changes
Looks good to me.

2023-03-14 16:49 UTC, merged