Adds a warning about editing to the containerd config.toml file
k3s-io/k3s pull request #7057
Opened 2023-03-10 18:01 UTC by dereknola

#### Proposed Changes ####
- Adds a warning to the top of `/var/lib/rancher/k3s/agent/etc/containerd/config.toml` file that it should not be edited, as we autogenerate that file on startup/restart. 

#### Types of Changes ####
Bug Fix

#### Verification ####
- Start K3s
- Check that `/var/lib/rancher/k3s/agent/etc/containerd/config.toml` has a comment at the top of the file about not editing it.

#### Linked Issues ####
https://github.com/k3s-io/k3s/issues/7056

#### User-Facing Change ####

```release-note

```

#### Further Comments ####

2023-03-10 18:15 UTC, brandond requested changes

2023-03-10 18:15 UTC, brandond commented on pkg/agent/templates/templates_linux.go
> +# File generated by {{ .Program }}. DO NOT EDIT. Use config.toml.toml instead.
```suggestion
# File generated by {{ .Program }}. DO NOT EDIT. Use config.toml.tmpl instead.
```

2023-03-13 16:28 UTC, briandowns approved these changes

2023-03-13 20:34 UTC, brandond approved these changes

2023-03-13 20:42 UTC, merged