Update stable channel to v1.25.8+k3s1
k3s-io/k3s pull request #7161
Opened 2023-03-28 22:01 UTC by brooksn

#### Proposed Changes ####

#### Types of Changes ####

#### Verification ####

#### Testing ####

#### Linked Issues ####

#### User-Facing Change ####

```release-note

```

#### Further Comments ####

2023-03-28 22:02 UTC, cwayne18 commented
I think we should move to 1.26

2023-03-28 22:02 UTC, cwayne18 requested changes
Let's move to 1.26.3

2023-03-29 10:47 UTC, cwayne18 approved these changes

2023-03-29 16:42 UTC, dereknola approved these changes

2023-03-29 16:43 UTC, brandond approved these changes

2023-03-29 22:49 UTC, merged