Adding cli to custom klipper helm image
k3s-io/k3s pull request #7682
Opened 2023-06-07 18:55 UTC by vitorsavian

#### Proposed Changes ####

A new cli flag for changing our klipper helm image that is default

#### Types of Changes ####

New feature

#### Verification ####

```shell
drone exec --trusted --pipeline amd64
``` 

#### Testing ####

#### Linked Issues ####

https://github.com/k3s-io/k3s/issues/3865

#### User-Facing Change ####

```release-note

```

#### Further Comments ####

2023-06-07 19:13 UTC, brandond requested changes
Although the images are still called klipper-helm and klipper-lb, we don't call things "klipper" any more, even internally. Klipper was an early project name for K3s, and we've completely dropped except for these two image names.

2023-06-07 19:13 UTC, brandond commented on pkg/cli/cmds/server.go
> +		Destination: &ServerConfig.KlipperHelmImage,
```suggestion
		Name:        "helm-job-image",
		Usage:       "(helm) Default image to use for helm controller jobs",
		Destination: &ServerConfig.HelmJobImage,
```

2023-06-07 19:13 UTC, brandond commented on pkg/cli/server/server.go
> +	serverConfig.ControlConfig.KlipperHelmImage = cfg.KlipperHelmImage
```suggestion
	serverConfig.ControlConfig.HelmJobImage = cfg.HelmJobImage
```

2023-06-07 19:13 UTC, brandond commented on pkg/daemons/config/types.go
> +	KlipperHelmImage         string
```suggestion
	HelmJobImage         string
```

2023-06-07 19:13 UTC, brandond commented on pkg/server/server.go
> +	}
Only apply the system default registry if a custom job image hasn't been set; the custom job image should take precedence.
```suggestion
	if config.ControlConfig.HelmJobImage != "" {
		helmchart.DefaultJobImage = config.ControlConfig.HelmJobImage
	} else if config.ControlConfig.SystemDefaultRegistry != "" {
		helmchart.DefaultJobImage = config.ControlConfig.SystemDefaultRegistry + "/" + helmchart.DefaultJobImage
	}
```

2023-06-07 20:45 UTC, brandond requested changes
nit, lgtm otherwise!

2023-06-07 20:45 UTC, brandond commented on pkg/cli/cmds/server.go
> +		Usage:       "(helm) Default image to use for helm controller",
clarify that this is for helm jobs, not the controller. the controller that creates jobs runs in the main k3s process.
```suggestion
		Usage:       "(helm) Default image to use for helm jobs",
```

2023-06-12 23:40 UTC, brandond approved these changes

2023-06-14 18:04 UTC, galal-hussein approved these changes

2023-06-28 15:31 UTC, merged