Add commands to disconnect tailscale interface in k3s-killall.sh
k3s-io/k3s pull request #7777
Opened 2023-06-14 09:59 UTC by manuelbuil

#### Proposed Changes ####

When k3s gets removed from the node, the tailscale interface should be disconnected from the tailnet. To do so, the best way is by doing:
```
tailscale down
tailscale logout
systemctl restart tailscaled
```
This PR adds those commands to k3s-killall.sh

#### Types of Changes ####

Bugfix

#### Verification ####

After running k3s-killall.sh, the tailscale interface should not have any IP and running `tailscale status --json` should not report anything because we logged out

#### Testing ####

#### Linked Issues ####

https://github.com/k3s-io/k3s/issues/7772

#### User-Facing Change ####

```release-note

```

#### Further Comments ####

2023-06-14 15:41 UTC, brandond reviewed
I'm a little concerned that this will be a breaking change for anyone using tailscale standalone. I know from GH issue that there are users that are currently deploying tailscale by hand, and then installing k3s afterwards. Is there anything we can do to avoid breaking things? Is there some way to uniquely configure tailscale to indicate that it is managed by k3s, and check for that when uninstalling?

2023-06-14 16:16 UTC, manuelbuil commented
> I'm a little concerned that this will be a breaking change for anyone using tailscale standalone. I know from GH issues that there are users that are currently deploying tailscale by hand, and then installing k3s afterwards. Is there anything we can do to avoid breaking things? Is there some way to uniquely configure tailscale to indicate that it is managed by k3s, and check for that when uninstalling?

Ok, I did not think about this use case TBH. Instead of turning it off, we could remove the configured subnet route instead, which is what we basically do apart from starting and logging. That would still fix the issue. Let me update the PR

2023-06-14 16:35 UTC, dereknola approved these changes

2023-06-14 16:41 UTC, brandond requested changes

2023-06-14 16:41 UTC, brandond commented on install.sh
> +    if [[ -n $(command -v tailscale) ]]; then
Single braces only, this isn't bash. And quote the potentially empty subshell output.

```suggestion
    if [ -n "$(command -v tailscale)" ]; then
```

2023-06-14 17:11 UTC, brandond approved these changes

2023-06-14 18:29 UTC, merged

2023-09-15 15:37 UTC, DerRockWolf commented
> I'm a little concerned that this will be a breaking change for anyone using tailscale standalone. I know from GH issues that there are users that are currently deploying tailscale by hand, and then installing k3s afterwards. Is there anything we can do to avoid breaking things? Is there some way to uniquely configure tailscale to indicate that it is managed by k3s, and check for that when uninstalling?

Removing the advertised routes is also somewhat breaking, if one is using manually created advertised routes.

Is the `k3s-killall.sh` script being executing automatically at some point, or is it always run manually?
If it's only run manually I'm fine with it removing the advertised routes.

2023-09-15 15:39 UTC, brandond commented
It is never run automatically. An administrator has to chose to run the uninstall or killall script, although a killall is also run as part of the uninstall (for obvious reasons).

2023-09-18 07:37 UTC, manuelbuil commented
We have this related issue in the backlog: https://github.com/k3s-io/k3s/issues/8012