fix image_scan.sh script and download trivy version
k3s-io/k3s pull request #7950
Opened 2023-07-12 15:37 UTC by osodracnai

#### Proposed Changes ####
This references to the bump trivy version PR https://github.com/k3s-io/k3s/pull/7738 and also https://github.com/k3s-io/k3s/issues/7949
It removes the 32 bit archs from download and adds the now supported s390x arch

#### Types of Changes ####

#### Verification ####

#### Testing ####

#### Linked Issues ####

#### User-Facing Change ####

```release-note

```

#### Further Comments ####

2023-07-12 19:52 UTC, dereknola approved these changes

2023-07-13 17:03 UTC, brandond requested changes

2023-07-13 17:03 UTC, brandond commented on Dockerfile.dapper
> +
nit: remove unnecessarily added whitespace

2023-07-13 17:07 UTC, brandond approved these changes

2023-07-13 18:03 UTC, merged