add --disable-cloud-controller and --disable-kube-proxy test
k3s-io/k3s pull request #8018
Opened 2023-07-20 12:06 UTC by osodracnai

#### Proposed Changes ####

#### Types of Changes ####

#### Verification ####

#### Testing ####

#### Linked Issues ####

#### User-Facing Change ####

```release-note

```

#### Further Comments ####

2023-07-20 15:57 UTC, brandond requested changes

2023-07-20 15:57 UTC, brandond commented on tests/integration/kubeflags/kubeflags_test.go
> +		--cloud-node-lifecycle
This comment is not accurate - what it does is append `,-cloud-node,-cloud-node-lifecycle` to the end of the `--controllers` flag.

2023-07-20 16:18 UTC, brandond commented on tests/integration/kubeflags/kubeflags_test.go
> +		https://github.com/k3s-io/k3s/blob/master/docs/adrs/servicelb-ccm.md
Another note on this - if you use --disable-cloud-controller and --disable=servicelb together, the CCM **will** be entirely disabled and prevented from running at all. You might want to cover this case in or alongside this test.

2023-07-20 19:12 UTC, dereknola requested changes

2023-07-20 19:12 UTC, dereknola commented on tests/integration/kubeflags/kubeflags_test.go
> +		It("kills previous server, clean logs and start up with no problems and disabled kube-proxy and cloud controller", func() {
Create a new `When` Block for this entire subtest
```suggestion
            When("server is setup without cloud controller components")
		It("kills previous server, clean logs and start up with no problems and disabled kube-proxy and cloud controller", func() {
```

Also, seperate the `Kill server and cleanup` and put the `It` in the previous section.

2023-07-20 19:12 UTC, dereknola commented on tests/integration/kubeflags/kubeflags_test.go
> +		It("kills previous server, clean logs and start up with no problems and all disabled cloud controller", func() {
Separate the Kill server and Clean logs into an independent `It`

2023-07-21 16:41 UTC, dereknola approved these changes

2023-07-24 19:53 UTC, brandond approved these changes

2023-08-04 17:27 UTC, merged