Add --image-service-endpoint flag and default to value of --container…
k3s-io/k3s pull request #8279
Opened 2023-08-30 15:55 UTC by hinshun

#### Proposed Changes ####

Problem:
External container runtime can be set but image service endpoint is unchanged and also is not exposed as a flag. This is useful for using containerd snapshotters outside of the ones that have built-in support like stargz-snapshotter.

Solution:
Add a flag --image-service-endpoint and also default image service endpoint to container runtime endpoint if set.

#### Types of Changes ####

The `--image-service-endpoint` flag is a new feature but defaulting image-service-endpoint can be considered a bug fix as that's the behavior in most CRI related tool like `crictl`.

#### Verification ####

Use `--container-runtime-endpoint` to an external containerd instead of `--snapshotter` for any remote snapshotter setup like `stargz` or `nydus`. Optionally set `--image-service-endpoint` if the snapshotter also supports the image service GRPC server.

#### Testing ####

#### Linked Issues ####

#### User-Facing Change ####

```release-note
Add `--image-service-endpoint` flag to specify an external image service socket.
```

2023-08-30 17:02 UTC, hinshun commented on pkg/agent/config/config.go
> +	if !nodeConfig.Docker {
In the latest revision, I didn't end up moving the logic down. I realized it's more correct to set:
```go
nodeConfig.AgentConfig.ImageServiceSocket = nodeConfig.ContainerRuntimeEndpoint
```
Compared to previously:
```go
nodeConfig.AgentConfig.ImageServiceSocket = nodeConfig.AgentConfig.RuntimeSocket
```

2023-09-01 18:45 UTC, hinshun commented
Test failures don't seem related:
cc @brandond

```sh
 Repository 'Main Update Repository' is invalid.
[repo-update|http://download.opensuse.org/update/leap/15.4/oss/] Valid metadata not found at specified URL
History:
 - File './repodata/f13a28ea4c16be025e7f3735dcb751e40beee3ce7ea014bb7a94e4b5a94f8fea-deltainfo.xml.gz' not found on medium 'http://download.opensuse.org/update/leap/15.4/oss/'
 - Can't provide ./repodata/f13a28ea4c16be025e7f3735dcb751e40beee3ce7ea014bb7a94e4b5a94f8fea-deltainfo.xml.gz
 ```
 
 ```sh
SSH: ssh mCGsdq26Uu4AbG5sgkLwS3Qkx@sfo2.tmate.io
or: ssh -i <path-to-private-SSH-key> mCGsdq26Uu4AbG5sgkLwS3Qkx@sfo2.tmate.io
Error: The action has timed out.
```

2023-09-01 18:48 UTC, brandond commented
Yeah, sometimes the opensuse repos have issues. We can just re-run.

2023-09-27 16:53 UTC, dereknola requested changes

2023-09-27 16:53 UTC, dereknola commented on pkg/cli/cmds/agent.go
> +		Usage:       "(agent/runtime) Disable embedded containerd image service and use remote image service socket at the given path. If not specified, it will the same with --container-runtime-endpoint b
```suggestion
		Usage:       "(agent/runtime) Disable embedded containerd image service and use remote image service socket at the given path. If not specified, defaults to --container-runtime-endpoint.",
```

2023-09-27 18:51 UTC, brandond approved these changes

2023-09-27 19:33 UTC, dereknola approved these changes

2023-09-27 19:58 UTC, brandond commented
will merge once CI is green.

2023-09-27 20:20 UTC, brandond commented
Test are flaking on s390x because this branch is missing CI fixes from master. We could rebase and re-run tests again, but I'm not worried about it. Merging.

2023-09-27 20:20 UTC, merged