Add context to flannel errors
k3s-io/k3s pull request #8284
Opened 2023-08-31 15:45 UTC by manuelbuil

#### Proposed Changes ####

Add extra context to the flannel errors to simplify debugging exercises

#### Types of Changes ####

Bugfix

#### Verification ####

Try to create an error and see the new extra information in the logs

#### Testing ####

#### Linked Issues ####

https://github.com/k3s-io/k3s/issues/8278

#### User-Facing Change ####

```release-note

```

#### Further Comments ####

2023-09-05 18:22 UTC, dereknola requested changes

2023-09-05 18:22 UTC, dereknola commented on pkg/agent/flannel/flannel.go
> +		return errors.Wrap(err, "failed to find the interface")
Looks like you need to import `errors`

2023-09-07 17:36 UTC, dereknola approved these changes

2023-09-07 19:46 UTC, brandond approved these changes

2023-09-25 06:20 UTC, merged