Include the interface name in the error message
k3s-io/k3s pull request #8346
Opened 2023-09-13 14:00 UTC by manuelbuil

#### Proposed Changes ####

Add the name of the interface to the error messages to help debugging

#### Types of Changes ####

Bugfix

#### Verification ####

Use k3s rootless as querying the interface will fail

#### Testing ####

#### Linked Issues ####

https://github.com/k3s-io/k3s/issues/8345

#### User-Facing Change ####

```release-note

```

#### Further Comments ####

2023-09-13 14:01 UTC, osodracnai approved these changes

2023-09-13 16:00 UTC, dereknola approved these changes

2023-09-13 16:59 UTC, brandond requested changes
`:` is usually used to delimit separate messages in the error stack, we should avoid using it as part of the message.

2023-09-13 16:59 UTC, brandond commented on pkg/agent/config/config.go
> +			return nil, errors.Wrapf(err, "unable to find interface: %s", envInfo.FlannelIface)
```suggestion
			return nil, errors.Wrapf(err, "unable to find interface %s", envInfo.FlannelIface)
```

2023-09-13 16:59 UTC, brandond commented on pkg/util/net.go
> +		return "", fmt.Errorf("interface: %s does not have a correct global unicast ip: %w", ifaceName, err)
```suggestion
		return "", fmt.Errorf("interface %s does not have a valid global unicast ip: %w", ifaceName, err)
```

2023-09-14 08:05 UTC, manuelbuil commented on pkg/agent/config/config.go
> +			return nil, errors.Wrapf(err, "unable to find interface: %s", envInfo.FlannelIface)
ok, thanks!

2023-09-14 23:50 UTC, brandond approved these changes

2023-09-25 08:27 UTC, brandond approved these changes

2023-09-25 14:50 UTC, merged