Update to v1.28.2 and go to v1.20.8
k3s-io/k3s pull request #8351
Opened 2023-09-13 22:34 UTC by johnatasr

#### Proposed Changes ####

#### Types of Changes ####

#### Verification ####

#### Testing ####

#### Linked Issues ####

#### User-Facing Change ####

```release-note

```

#### Further Comments ####

2023-09-13 23:17 UTC, brandond requested changes
```
Unexpected go version go1.21.1 linux/amd64 - Kubernetes v1.28.2 should be built with go version go1.20.8
```

2023-09-13 23:26 UTC, briandowns commented on .github/workflows/integration.yaml
> +        go-version: '1.21.1'
Only master is using 1.21 right now. THis should be 1.20.8.

2023-09-14 00:19 UTC, briandowns approved these changes

2023-09-14 04:12 UTC, brandond approved these changes
lgtm; make sure to squash when merging.

2023-09-14 20:35 UTC, closed without merging

2023-09-15 08:44 UTC, Silvest89 commented
@johnatasr Why did you close this? :paintbrush: