Use IPv6 in case is the first configured IP with dualstack
k3s-io/k3s pull request #8581
Opened 2023-10-10 10:58 UTC by rbrtbnfgl

#### Proposed Changes ####

Use always IPv6 when the first configured `node-ip` is IPv6 also in case of dualstack.
This fix also will always use the configured `node-ip` on kubelet to address https://github.com/rancher/rke2/issues/4759
In case of dualstack `node-ip` it adds `CloudDualStackNodeIPs=true` as `feature-gates` configuration to fix https://github.com/k3s-io/k3s/pull/6023 from k8s 1.27 version and it doesn't require to add `node-ip=0.0.0.0` within the kubelet args.
The PR also fix https://github.com/k3s-io/k3s/issues/8467#issuecomment-1749125924 showing the IPv6 when listing pods.

#### Types of Changes ####

#### Verification ####

#### Testing ####

#### Linked Issues ####

#8467

#### User-Facing Change ####

```release-note

```

#### Further Comments ####

2023-10-10 16:30 UTC, dereknola requested changes
Since the kube-arg of 0.0.0.0 is no longer required, please modify the E2E dualstack test and remove those arguments with this PR.

2023-10-10 16:53 UTC, dereknola approved these changes

2023-10-10 17:03 UTC, manuelbuil commented
Since `CloudDualStackNodeIPs=true` starts in 1.27, we won't be able to backport it to all branches. What if you split the PR into two commits? One without the  `CloudDualStackNodeIPs=true` which can be backported to 1.25 and 1.26 and one with the  `CloudDualStackNodeIPs=true` (or two PRs, whatever is easier to you)

2023-10-11 07:42 UTC, rbrtbnfgl commented
I already edited a different commit for 1.26 and 1.25. The fix is not working and kubelet is still prioritising the IPv4 as pod IP on those versions.

2023-10-12 23:11 UTC, brandond approved these changes

2023-10-13 08:23 UTC, merged