Disable helm CRD installation for disable-helm-controller
k3s-io/k3s pull request #8702
Opened 2023-10-19 21:35 UTC by harsimranmaan

The NewContext package requires config as input which would require all third-party callers to update when the new go module is published.

This change only affects the behaviour of installation of helm CRDs. Existing helm crds installed in a cluster would not be removed when disable-helm-controller flag is set on the server.

Addresses #8701

#### Proposed Changes ####
Disable helm CRD installation for disable-helm-controller

#### Types of Changes ####
Breaking Change (for sdk) not for k3s service

#### Verification ####

#### Testing ####

#### Linked Issues ####
#8701 

#### User-Facing Change ####

```release-note

```

#### Further Comments ####

2023-10-19 21:45 UTC, brandond requested changes
I don't like passing in both a struct, and a field on that struct. Just pass in the Config struct, and use the `forServer` flag to determine which config to use.

2023-10-19 21:45 UTC, brandond commented on pkg/cli/etcdsnapshot/etcd_snapshot.go
> +	sc, err := server.NewContext(ctx, config, config.ControlConfig.Runtime.KubeConfigAdmin, false)
```suggestion
	sc, err := server.NewContext(ctx, config, false)
```

2023-10-19 21:45 UTC, brandond commented on pkg/server/context.go
>  	restConfig, err := clientcmd.BuildConfigFromFlags("", cfg)
```suggestion
func NewContext(ctx context.Context, config *Config, forServer bool) (*Context, error) {
	var cfg string
	if forServer {
		cfg = config.ControlConfig.Runtime.KubeConfigSupervisor
	} else {
		cfg = config.ControlConfig.Runtime.KubeConfigAdmin
	}
	restConfig, err := clientcmd.BuildConfigFromFlags("", cfg)
```

2023-10-19 21:45 UTC, brandond commented on pkg/server/context.go
> +		if err := registerCrds(ctx, serverConfig, restConfig); err != nil {
```suggestion
		if err := registerCrds(ctx, config, restConfig); err != nil {
```

2023-10-19 21:45 UTC, brandond commented on pkg/server/context.go
> +func registerCrds(ctx context.Context, serverConfig *Config, restConfig *rest.Config) error {
```suggestion
func registerCrds(ctx context.Context, config *Config, restConfig *rest.Config) error {
```

2023-10-19 21:45 UTC, brandond commented on pkg/server/context.go
> +	if serverConfig == nil || !serverConfig.ControlConfig.DisableHelmController {
```suggestion
func crds(config *Config) []crd.CRD {
	defaultCrds := addoncrd.List()
	if serverConfig == nil || !config.ControlConfig.DisableHelmController {
```

2023-10-19 21:45 UTC, brandond commented on pkg/server/server.go
> +	sc, err := NewContext(ctx, config, controlConfig.Runtime.KubeConfigSupervisor, true)
```suggestion
	sc, err := NewContext(ctx, config, true)
```

2023-10-19 22:45 UTC, brandond approved these changes

2023-10-19 22:45 UTC, brandond commented
LGTM! We can squash when merging.

2023-10-24 05:44 UTC, harsimranmaan commented
Hi @brandond, lemme know if this require any further work. Feel free to merge it

2023-10-24 06:58 UTC, brandond commented
You're all set.We're in code freeze pending release of last week's patches. We will merge things again once the releases are out.

2023-11-15 17:03 UTC, dereknola approved these changes

2023-11-15 22:33 UTC, brandond commented
arm and s390x are flaking; merging

2023-11-15 22:35 UTC, merged