Tweaked order of ingress IPs in ServiceLB
k3s-io/k3s pull request #8711
Opened 2023-10-22 21:02 UTC by jsnctl

Previously, ingress IPs were only string-sorted when returned

Sorted by IP family and string-sorted in each family as part of filterByIPFamily method

#### Proposed Changes ####

Addresses https://github.com/k3s-io/k3s/issues/8704 with adjustment and use of `filterByIPFamily` as part of `servicelb.getStatus`

#### Types of Changes ####

Bugfix

#### Verification ####

Added new unit test to `servicelb_test.go`

#### Testing ####

See above

#### Linked Issues ####

https://github.com/k3s-io/k3s/issues/8704

#### User-Facing Change ####

```release-note
Improved ingress IP ordering from ServiceLB
```

#### Further Comments ####

Hopefully my first PR of many. Great project

2023-10-24 01:02 UTC, brandond requested changes
thanks! one nit but lgtm otherwise.

2023-10-24 01:02 UTC, brandond commented on pkg/cloudprovider/servicelb.go
> +	}
With your change to `filterByIPFamily` you can actually get rid of this entirely... the list comes from `k.podIPs` which already calls `filterByIPFamily`.
```suggestion
```

2023-10-24 20:16 UTC, jsnctl commented
CI is failing but see that in other PRs so guess this is a known issue? Holding off merge until code freeze is up too?

2023-10-24 20:21 UTC, brandond commented
No, it looks like your formatting is off.
> `pkg/cloudprovider/servicelb.go:288: File is not `gofmt`-ed with `-s` (gofmt)`

2023-11-02 11:27 UTC, jsnctl commented
Anything further to pick up on this PR with the formatting fixed @brandond?

2023-11-09 01:14 UTC, brandond approved these changes

2023-11-15 17:02 UTC, dereknola approved these changes

2023-11-15 22:32 UTC, brandond commented
s390x is flaking; merging

2023-11-15 22:33 UTC, merged