add agent flag disable-agent-lb
k3s-io/k3s pull request #8717
Opened 2023-10-24 11:37 UTC by chenk008

#### Proposed Changes ####

Add agent flag disable-agent-lb

#### Types of Changes ####

New Feature

#### Verification ####

#### Testing ####

#### Linked Issues ####

https://github.com/k3s-io/k3s/issues/8651

#### User-Facing Change ####

```release-note
Add agent flag disable-agent-lb, it will disable agent load balance proxy.

```

#### Further Comments ####

2023-10-24 21:15 UTC, brandond requested changes

2023-10-25 16:27 UTC, dereknola approved these changes

2023-11-08 08:50 UTC, chenk008 commented
@brandond Please help to merge this change.

2023-11-09 01:15 UTC, brandond approved these changes

2023-11-14 23:53 UTC, brandond commented
s390x flaked; merging

2023-11-14 23:54 UTC, merged