Add ability to install K3s PR Artifact from GitHub
k3s-io/k3s pull request #9185
Opened 2024-01-09 18:50 UTC by dereknola

#### Proposed Changes ####
Conext: With the removal of AWS S3 uploads for K3s PRs, we need another way for QA to easily validate open PR builds of K3s.

- Adds the ability for the install script to pull the K3s executable built during GitHub CI (specifically the integration test build step found [here](https://github.com/k3s-io/k3s/blob/master/.github/workflows/build-k3s.yaml))

- Enables the optional use of a GITHUB_TOKEN exported by the user to get around the 60 GH API calls per hour limit. This feature makes 4 API calls per use. Using a token, users can make 5000 calls per hour, so QA should have no problems running multiple PR tests per day with this. 

#### Types of Changes ####
Install script feature

#### Verification ####

#### Testing ####

#### Linked Issues ####

#### User-Facing Change ####

```release-note

```

#### Further Comments ####

2024-01-09 22:37 UTC, brandond requested changes

2024-01-09 22:37 UTC, brandond commented on install.sh.sha256sum
> +c3faabf3d40d51870cb3ce5df44ac5c45ce6597443e4e7e9653015dbae0b3c5a  ./install.sh
just the filename, no relative or absolute path
```suggestion
c3faabf3d40d51870cb3ce5df44ac5c45ce6597443e4e7e9653015dbae0b3c5a  install.sh
```

2024-01-19 22:04 UTC, brandond approved these changes

2024-01-24 17:03 UTC, vitorsavian approved these changes

2024-02-07 00:30 UTC, merged