Disable color outputs using `RAW_OUTPUT` env var
k3s-io/k3s pull request #9357
Opened 2024-02-06 07:57 UTC by rishinair11

#### Proposed Changes ####
Setting this environment variable will not wrap the text in ANSI color codes, so that we can print a raw output.
This helps us a lot when piping the output to a text file, ANSI color codes make it difficult to read through the output in a text editor.

#### Types of Changes ####

Introduced a new environment variable called `RAW_OUTPUT`.
`RAW_OUTPUT=1` will disable the wrapping of output text in ANSI color codes.
Default functionality will be maintained if the env var is not set at all.

#### Verification ####

#### Testing ####

Ran this suit of tests:
- Default usage:   
   <img width="1024" alt="image" src="https://github.com/k3s-io/k3s/assets/42700059/3f2e963a-e4b8-4b9b-8bd1-0c13611d512a">
- Usage with env var:
   <img width="1018" alt="image" src="https://github.com/k3s-io/k3s/assets/42700059/6e7134b5-07f0-4779-b1d6-2ea15cb0bf9c">

#### Linked Issues ####

Fixes #9355 

#### User-Facing Change ####

```release-note
To enable raw output for the `check-config` subcommand, run:

RAW_OUTPUT=1 k3s check-config
```

#### Further Comments ####

Let me know if the variable name is not suitable, or any other questions/discussions. Will be happy to refactor my solution if needed.

2024-02-06 18:14 UTC, brandond requested changes

2024-02-06 18:14 UTC, brandond commented on contrib/util/check-config.sh
> +  if [ $RAW_OUTPUT -eq 1 ]; then
this seems fine, but an even more minimal change might be to make `color()` return early if this env var is set?

Also, I think [`NO_COLOR`](https://www.gnu.org/software/gettext/libtextstyle/manual/html_node/The-NO_005fCOLOR-variable.html) is a more widely supported variable to use for this. If it is set to anything other than an empty string, color output should be suppressed.

2024-02-29 20:26 UTC, brandond approved these changes

2024-02-29 20:27 UTC, brandond requested changes

2024-02-29 20:27 UTC, brandond commented on contrib/util/check-config.sh
> +  if [[ -n "$NO_COLOR" ]]; then
Nit: posix sh `[]` not bash `[[]]`
```suggestion
  if [ -n "$NO_COLOR" ]; then
```

2024-03-02 06:04 UTC, brandond approved these changes

2024-03-03 07:10 UTC, rishinair11 commented
Thank you for the review @brandond. 
Is there something more I have to do to get this merged? Let me know, thank you.

2024-03-05 00:30 UTC, brandond commented
No, you are set. We are working through some issues with scheduling work for the next release cycle, so this may remain on hold for a bit longer.

2024-03-05 23:10 UTC, merged