Update Kubernetes to v1.27.11
k3s-io/k3s pull request #9491
Opened 2024-02-14 21:39 UTC by brooksn

Updates Kubernetes to v1.27.11 and Go to 1.21.7.

2024-02-14 23:31 UTC, brandond requested changes

2024-02-14 23:31 UTC, brandond commented on go.mod
> +go 1.21
Upstream is still on `go 1.20`, can we leave this as-is?
https://github.com/kubernetes/kubernetes/blob/release-1.27/go.mod#L9

```suggestion
go 1.20
```

2024-02-15 20:08 UTC, brandond approved these changes

2024-02-15 20:08 UTC, tashima42 approved these changes

2024-02-15 20:29 UTC, galal-hussein approved these changes

2024-02-15 21:14 UTC, merged