Update Kubernetes to v1.28.7
k3s-io/k3s pull request #9492
Opened 2024-02-14 21:39 UTC by brooksn

Updates Kubernetes to v1.28.7 and Go to 1.21.7.

2024-02-14 23:34 UTC, brandond requested changes

2024-02-14 23:34 UTC, brandond commented on go.mod
> +go 1.21
Upstream is still on `go 1.20`, can we leave this as-is?
https://github.com/kubernetes/kubernetes/blob/release-1.28/go.mod#L9

```suggestion
go 1.20
```

2024-02-15 01:47 UTC, brandond commented
```
panic: 757695334: duplicate method InformerFor

goroutine 28141 [running]:
go/types.computeInterfaceTypeSet(0x0, 0xc000000006?, 0xc014d67900)
	go/types/typeset.go:323 +0xb65
go/types.(*Interface).typeSet(...)
	go/types/interface.go:29
go/types.(*Interface).Complete(...)
	go/types/interface.go:143
golang.org/x/tools/internal/gcimporter.readUnifiedPackage(0xc00416e1c0, 0x0, 0xc0090da5a0, {0x1, 0x0, {0xc0030199c0, 0x3c}, {0xc05f6c3850, 0x52173}, {0xc027cce000, ...}, ...})
	golang.org/x/tools@v0.6.0/internal/gcimporter/ureader_yes.go:121 +0x4d8
golang.org/x/tools/internal/gcimporter.UImportData(0x133ee20?, 0xc0307435a8?, {0xc05f3fe001?, 0x4c?, 0xc0090da5a0?}, {0xc0030199c0, 0x3c})
	golang.org/x/tools@v0.6.0/internal/gcimporter/ureader_yes.go:68 +0x10a
golang.org/x/tools/go/gcexportdata.Read({0x133ee20?, 0xc0307435a8?}, 0x0?, 0x10?, {0xc0030199c0, 0x3c})
	golang.org/x/tools@v0.6.0/go/gcexportdata/gcexportdata.go:140 +0x270
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).loadFromExportData(0xc003199f20?)
	github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_loadingpackage.go:221 +0x331
```

Might need to update golangci-lint for golang 1.21

2024-02-15 20:08 UTC, brandond approved these changes

2024-02-15 20:08 UTC, tashima42 approved these changes

2024-02-15 20:28 UTC, galal-hussein approved these changes

2024-02-15 21:15 UTC, merged