Updating the script binary_size_check to complete the command name by…
k3s-io/k3s pull request #9992
Opened 2024-04-22 06:42 UTC by ag6221254

… adding .exe extension to the k3s binary name to make it available to run stat command

#### Proposed Changes ####

This is the Modification in K3s agent for Windows port. This pull request is focused on:

1. Updating the script binary_size_check.sh to complete the command name by adding .exe extension to the k3s binary name to make it available to run stat command

#### Types of Changes ####

BugFix

#### Verification ####

Run GOOS=windows CXX=x86_64-w64-mingw32-g++ CC=x86_64-w64-mingw32-gcc SKIP_VALIDATE=true ./scripts/ci on Ubuntu machine to proof build Windows port.

NOTE: You may need to install the following packages to build:

sudo apt-get install mingw-w64
sudo apt-get install zstd

#### Testing ####

We Can follow same testing steps as mentioned in the PR - https://github.com/k3s-io/k3s/pull/7259

#### Linked Issues ####

https://github.com/k3s-io/k3s/issues/9991

#### User-Facing Change ####

None
```release-note

```

#### Further Comments ####
None

2024-05-02 08:51 UTC, ag6221254 commented
Looking for reviews and approval on the above PR.

2024-05-06 22:26 UTC, brandond approved these changes

2024-05-06 22:26 UTC, brandond requested changes
LGTM, but please sign-off your commits for DCO.

2024-05-07 05:17 UTC, brandond commented
You'll need to rebase, squash, sign-off a single commit, and then force-push to the branch. I'm still seeing DCI failure and a merge commit.

2024-05-07 10:35 UTC, ag6221254 commented
ohh ok. Corrected!

2024-05-08 08:41 UTC, brandond approved these changes

2024-05-13 07:08 UTC, ag6221254 commented
Can I please get 1 more approval ?

2024-05-13 07:53 UTC, manuelbuil approved these changes

2024-05-13 07:56 UTC, ag6221254 commented
Thank you for the approvals. Can we also please get it merged from the authorized user ?

2024-05-13 17:38 UTC, brandond commented
No. We are in code freeze for the May patch releases.

2024-05-28 20:30 UTC, merged